// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8uEZuEtR6enR9hxlxGSFbvs6UtciiSc',
    appId: '1:620874623384:web:65840e127729f70bf423ed',
    messagingSenderId: '620874623384',
    projectId: 'lv-app-807ab',
    authDomain: 'lv-app-807ab.firebaseapp.com',
    storageBucket: 'lv-app-807ab.firebasestorage.app',
    measurementId: 'G-HBPK8T6K2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7OHzzN04ibEkapOZ_TBBBDln5ydBI6Zc',
    appId: '1:620874623384:android:97c4c4729193ca07f423ed',
    messagingSenderId: '620874623384',
    projectId: 'lv-app-807ab',
    storageBucket: 'lv-app-807ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8O66oLqWSmgioVQ5CHU3ecg4ypIkgDrE',
    appId: '1:620874623384:ios:10d8a380e9e8a0b6f423ed',
    messagingSenderId: '620874623384',
    projectId: 'lv-app-807ab',
    storageBucket: 'lv-app-807ab.firebasestorage.app',
    iosBundleId: 'com.example.lv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8O66oLqWSmgioVQ5CHU3ecg4ypIkgDrE',
    appId: '1:620874623384:ios:10d8a380e9e8a0b6f423ed',
    messagingSenderId: '620874623384',
    projectId: 'lv-app-807ab',
    storageBucket: 'lv-app-807ab.firebasestorage.app',
    iosBundleId: 'com.example.lv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv8uEZuEtR6enR9hxlxGSFbvs6UtciiSc',
    appId: '1:620874623384:web:edd8a4ed9398f2c3f423ed',
    messagingSenderId: '620874623384',
    projectId: 'lv-app-807ab',
    authDomain: 'lv-app-807ab.firebaseapp.com',
    storageBucket: 'lv-app-807ab.firebasestorage.app',
    measurementId: 'G-BMK8V5DHDB',
  );
}
